//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pc_game {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lb_id;
		
		protected System.Web.UI.WebControls.TextBox txt_id;
		
		protected System.Web.UI.WebControls.Label lb_name;
		
		protected System.Web.UI.WebControls.TextBox txt_name;
		
		protected System.Web.UI.WebControls.Label lb_image;
		
		protected System.Web.UI.WebControls.TextBox txt_image;
		
		protected System.Web.UI.WebControls.Label lb_link;
		
		protected System.Web.UI.WebControls.TextBox txt_link;
		
		protected System.Web.UI.WebControls.Label lb_type;
		
		protected System.Web.UI.WebControls.TextBox txt_type;
		
		protected System.Web.UI.WebControls.Button btn_save;
		
		protected System.Web.UI.WebControls.Button btn_clear;
		
		protected System.Web.UI.WebControls.PlaceHolder DBDataPlaceHolder;
		
		protected System.Web.UI.WebControls.GridView Grid;
	}
}
